### ISSUE TITLE
What parameters need to be adjusted when generating frames of other resolutions?

### ISSUE THREAD

**Issue by ReedOnePeck** [NVlabs/long-video-gan#2]
I appreciate your work very much！！！But I encountered some problems when I tried to do it myself, and I need to ask you for advice.

When I used this data（https://nvlabs-fi-cdn.nvidia.com/long-video-gan/datasets/biking/0144x0256/） to train the low_resolution model, After modifying height = 144 and width = 256 in lres.py, errors will still be reported during training.
File "/data/home/cddu/pythonProject/code/lyz_CV/long-video-gan-main/torch_utils/misc.py", line 95, in assert_shape
      raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}')
AssertionError: Wrong size for dimension 3: got 36, expected 144

It seems that the open source code was originally used for the resolution of 36 * 64, so I would like to ask where it needs to be modified if this code is to be used for other resolutions?

**Comment by pratul20591** [comment]
@ReedOnePeck @timothybrooks 
Did you got the solution for above query?
Using this code, I want to train and generate videos of 256 * 256 resolution.
Where all do we need to modify the code for training and generating 256 * 256 resolution videos?

**Comment by timothybrooks** [comment]
Hello! To train at different resolutions requires setting height and width in train_lres.py as well as lr_height and hr_height in train_sres.py. For example, to train on square images, set [this](https://github.com/NVlabs/long-video-gan/blob/main/train_lres.py#L263) to 64, [this](https://github.com/NVlabs/long-video-gan/blob/main/train_sres.py#L298) to 64, and [this](https://github.com/NVlabs/long-video-gan/blob/main/train_sres.py#L300) to 256. Please also note that for different datasets and different resolutions you may need to increase or decrease the value for the `--gamma` flag.
