### ISSUE TITLE
How to avoid low-performance memory layout?

### ISSUE THREAD

**Issue by kingsj0405** [NVlabs/long-video-gan#3]
I got the warning from following code.

https://github.com/NVlabs/long-video-gan/blob/4151a8b67d2194f829d21753dc2b405d88c0e13d/torch_utils/ops/filtered_lrelu.py#L208-L211

I wonder how to debug the problem in proper way. e.g. swapping before filteredLRelu?, adjusting tensor size at the begging of model?
Thank you:)

**Comment by timothybrooks** [comment]
Hi @kingsj0405, I am not sure, since the filtered lrelu code was written by StyleGAN3 authors and was copied for this project. I recommend asking on the StyleGAN3 repo.
