### ISSUE TITLE
code is getting stuck into a infinite while loop of function "get_infinite_data_iter" in Utils.py

### ISSUE THREAD

**Issue by pratul20591** [NVlabs/long-video-gan#4]
@timothybrooks 
I am trying to run the LongVideoGAN code with just 1 partition of horseback dataset with batch size=28. I am using single A6000 GPU. I am not using distributed system.
While running it, the code is getting stuck into a infinite while loop of function "get_infinite_data_iter" in Utils.py. I have even waited for 2 days !!!
value of get_world_size= 1.
PFA snapshot.
I also tried to run the while loop by restricting it for a finite number. (line 223:  while epoch < 100000). But it gave a StopIteration Exception.
Please suggest any changes to overcome it.

![error](https://user-images.githubusercontent.com/39545269/219941401-6b7b91d7-7675-436b-81ab-a5bd0029e29d.jpg)

**Comment by timothybrooks** [comment]
Hi @pratul20591, an infinite loop might happen here if the data loader does not return any samples. In that case, it will continue in the outer while loop without the inner for loop yielding any data. You could debug this by first iterating over the dataset (outside of this function) and making sure it returns examples as you expect, then you can try iterating over the data loader directly by returning `loader` and iterating over examples in the loader to make sure it returns batches of examples as you expect. Once both of those are working you can wrap it in this infinite data iter helper function, or you could continue to just use the loader itself.
