### ISSUE TITLE
Available for UCF-101 or sky-time lapse?

### ISSUE THREAD

**Issue by jacob-kang** [NVlabs/long-video-gan#7]
Hi. Thanks for your grate work.

I wonder Does this model can take ucf 101 or sky time lapse dataset?

How to train those??

Thanks.

kind regards

**Comment by timothybrooks** [comment]
Hi @jacob-kang, I did this work while at NVIDIA, and received approval to release models trained on the horseback and mountain biking datasets, but did not receive approval to release models trained on the UCF-101 or SkyTimelapse datasets, so unfortunately I was not able to release those model weights.
